### ISSUE TITLE
Volume increase/decrease behavior is unexpected

### ISSUE THREAD

**Issue by eejd** [Doraemoe/Spotify-Plugin-for-Quicksilver#11]
When you use the trigger options for increasing volume and decreasing volume, the volume level wraps. This behavior is unexpected and atypical. (I think it would not be compatible with most human user interface guidelines.) If it is intentional, perhaps it should be optional? Ideally the volume adjustements would saturate at max(volume) and min(volume).

**Comment by Doraemoe** [comment]
This should be an easy fix. However, I'm hesitated to do anything on this plugin for now as this plugin is literally "broken" until Spotify and Facebook fix their server (see [this](https://github.com/Doraemoe/Spotify-Plugin-for-Quicksilver/wiki/Login-page-does-not-load) for more details).
