### ISSUE TITLE
Can't Build On My Own System

### ISSUE THREAD

**Issue by frederickfogerty** [Doraemoe/Spotify-Plugin-for-Quicksilver#3]
Hey

I can't seem to build the project on my own system, yet Quicksilver itself and other plugins build just fine, any ideas why?

These are basically my big issues. I've added the required things to the Source Tree, still can't get it to work.
![screen shot 2014-05-01 at 12 54 18 am](https://cloud.githubusercontent.com/assets/615334/2841396/961e36e4-d066-11e3-90b6-e1751cababc6.png)

I've also tried fiddling with the config to no avail.
![screen shot 2014-05-01 at 12 55 29 am](https://cloud.githubusercontent.com/assets/615334/2841413/bce7c13c-d066-11e3-944c-846e8f64a4b7.png)

Thanks
Fred

**Comment by Doraemoe** [comment]
Hi,

This plugin depends on quicksilver itself (https://github.com/quicksilver/Quicksilver) you need first build quicksilver, it will generate necessary files in /tmp/QS. after that, you could build this project without problem.

In addition, if you want to build the framework branch, you also need an API key from https://developer.spotify.com/ 

hope this will help.

**Comment by frederickfogerty** [comment]
Hey,

I had downloaded the source for Quicksilver and built it before I submitted my original question, so that's not the problem. 

I just want to build the plugin, not the framework, am I doing something wrong?

Regards
Fred

**Comment by Doraemoe** [comment]
These 20 issues are exactly the same if I forget to build Quicksilver before I build this plugin. Try not open this project in Xcode and build Quicksilver first, after built Quicksilver, open this project in Xcode and build it.
