### ISSUE TITLE
Spinning wheel when going to Preferences

### ISSUE THREAD

**Issue by jonathanalevi** [Doraemoe/Spotify-Plugin-for-Quicksilver#6]
I went to go to the preferences and authorize the plugin, but I just get a spinning wheel in the window on the top left.

Have you stopped developing and supporting this plugin?

**Comment by Doraemoe** [comment]
Will have a look in the weekend. Haven't been using Spotify recently.

**Comment by jonathanalevi** [comment]
Awesome, thanks for the super-speedy reply :) 

## 

Jonathan Levi
Entrepreneur & Eclectic
http://jle.vi http://jle.vi/
IL: +972 54 296 - 0318
US: +1(408) 318 - 2875

P.S. I recently published a #1 bestselling book on accelerated learning. Check it out! http://jle.vi/book

**Comment by Doraemoe** [comment]
Hi,
I cannot reproduce this problem, could you provide more details? Like which system you are using, in which step you get the problem? And have you tired to restart QS, delete and reinstall this plugin, or [clear cache](http://qsapp.com/wiki/FAQ#How_do_I_clear_Quicksilver.27s_cache.3F)?

**Comment by jonathanalevi** [comment]
<img width="848" alt="screen shot 2015-09-25 at 10 06 50" src="https://cloud.githubusercontent.com/assets/1540530/10094820/3113c11a-636d-11e5-8213-65d455b32108.png">

<img width="850" alt="screen shot 2015-09-25 at 10 07 44" src="https://cloud.githubusercontent.com/assets/1540530/10094835/55c4d850-636d-11e5-9859-2842096f4614.png">

<img width="601" alt="screen shot 2015-09-25 at 10 08 22" src="https://cloud.githubusercontent.com/assets/1540530/10094837/620cd3e2-636d-11e5-8a8d-26d3e674cab9.png">

Hope this helps. I uninstalled and reinstalled a few times, Quit quicksilver, cleared cache... That spinning wheel never stops spinning in the top left!

Thanks for your help!
JL

**Comment by Doraemoe** [comment]
Can you try [this](https://dl.dropboxusercontent.com/u/1660391/Spotify%20Plugin.qsplugin_beta.zip) new version to see if it works?

**Comment by jonathanalevi** [comment]
It does!!! Thank you!
I’ll play with it more now.

## 

Jonathan Levi
Entrepreneur & Eclectic
http://jle.vi http://jle.vi/
IL: +972 54 296 - 0318
US: +1(408) 318 - 2875

P.S. I recently published a #1 bestselling book on accelerated learning. Check it out! http://jle.vi/book

**Comment by Doraemoe** [comment]
Great! Just note there is a "follow" function in this beta version that doesn't work ATM and may cause QS crash, be sure to not use it.

**Comment by jonathanalevi** [comment]
Ok cool.
I just realized it's only for Spotify Web. I wonder if there's a way to adapt it to the Spotify app...?

Thanks
JL

## 

Jonathan Levi
Entrepreneur & Eclectic
My Profile: http://jle.vi
IL: +972 54 296 - 0318
US: +1(408) 318 - 2875
Please check out my bestselling book at http://jle.vi/book

**Comment by Doraemoe** [comment]
This plugin is for Spotify desktop app, but many actions do need you to login and have internet access. The reason is Spotify does not provide any local API/AppleScript to do them.

BTW, I've uploaded a new version, the follow artist function should now working, please download from the link in the readme file.

**Comment by jonathanalevi** [comment]
I'll try it out. Thanks so much for your attentive support. Is there somewhere I can make a donation to continue your development?

**Comment by jonathanalevi** [comment]
Also, by the way, things are still opening in Spotify Web Player - any ideas why? 

Edit: Nevermind, "Open URL" was the first option rather than "Play" - now I know ;) 

In that case, two pieces of feedback:
1. Even though "Open URL" and "Copy" and "Display as Large Text" are not selected as Actions that apply to Spotify Playlist catalogue results, they still show when I tab over
2. Even though I de-selected the checkboxes for 9 out of the 11 control items (like increase/decrease volume), they still show in the catalogue when I invoke Quicksilver. 

Hope this helps. 
JL

**Comment by Doraemoe** [comment]
I did write some priority code in this plugin but somehow it does not work. For now you could try to see if this solution works:

Select a playlist or track -- Tab to action and right arrow to list all actions -- Right click in front of Play and choose Make Default.

<img width="808" alt="2015-09-29 4 19 39" src="https://cloud.githubusercontent.com/assets/1129569/10157143/baeaf8ee-66ca-11e5-9f46-207a29de87fe.png">

I will look into other issues.

It's very kind of you to think about donation, if you are OK with Paypal, you could use [this link](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=PZ483KHWBR9HG&lc=AU&item_name=Yifan%20Jin&currency_code=AUD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted)

**Comment by jonathanalevi** [comment]
That worked like a charm. Awesome.
Sending you a little something now as a small token of my appreciation for all your hard work.

JL

## 

Jonathan Levi
Life Enthusiast
http://jle.vi http://jle.vi/
IL: +972 54 296 - 0318
US: +1(408) 318 - 2875

P.S. I recently published a #1 bestselling book on accelerated learning. Check it out! http://jle.vi/book
