### ISSUE TITLE
Save trigger does not appear to be working (related to #1)

### ISSUE THREAD

**Issue by eejd** [Doraemoe/Spotify-Plugin-for-Quicksilver#9]
The ability to save a song to my library appears not to be functioning.

Description:
I specified a  key combinations for saving the currently playing song to 'My Music'. I specified that Quicksilver should show it's window when the action is triggered. The songs do not appear to be saved (they are not in 'My Library' and they do not show the check mark designation).

Reproducibility:
Using different key combination triggers did not solve the problem. I don't know the best next steps to debug.

Versions:
Spotify 1.0.15.133
MacOS X 10.10.5
Quicksilver 1.3.1 (4013)

**Comment by Doraemoe** [comment]
I cannot reproduce this issue, do you have problem while you are using keyboard shortcut or the save function just does not work? The check mark in Spotify not always show correctly, but for me the song will always added to the top of the Songs in My Library.
